### ISSUE TITLE
research-data-lifecycle.png is not properly cut out

### ISSUE THREAD

**Issue by caroott** [nfdi4plants/arc-rdm.org#53]
[research-data-lifecycle.png](https://github.com/nfdi4plants/arc-website/blob/main/public/research-data-lifecycle.png) is not properly cut out, resulting in a spooky image in darkmode:
![image](https://github.com/user-attachments/assets/14251f48-0f2e-4df9-8833-375247edae4d)
This should be a better version:
![research-data-lifecycle](https://github.com/user-attachments/assets/b4e22fee-b844-4b4f-bae9-178f59f9db0f)

**Comment by Freymaurer** [comment]
The same issue exists for other images:

![image](https://github.com/user-attachments/assets/65a16e4f-a82c-4f99-90f9-37359620f525)

![image](https://github.com/user-attachments/assets/1ec0999f-624b-40ad-ad1a-972002984514)

**Comment by caroott** [comment]
Here are all images in higher quality than the previous i sent:
![ARC-isa-cwl-decorations](https://github.com/user-attachments/assets/bf260b56-11fe-4e3e-a39e-c1e0103bf762)
![research-data-lifecycle](https://github.com/user-attachments/assets/48ca3bd1-5140-4e93-9690-a1717f706d77)
![ro-crate-vs-scaffold](https://github.com/user-attachments/assets/cc1f9a76-e364-4515-8e55-b66cfa137504)

**Comment by Brilator** [comment]
We should probably create a new research data life cycle. The existing one is kindly adapted from here https://rdmkit.elixir-europe.org/data_life_cycle. 

And can we please use svg graphics instead of png? 

- You can easily export from pptx to svg
- svg is editable and scalable (good resolution)
- If needed one can use [Inkscape](https://inkscape.org) to edit
- or text replace (since svg is just a text file) to quickly update color schemes or edit typos / capitalization, etc. 
- there are vscode extension to at least preview svg file 

This way you can keep producing nice figures in PPTX, but others could reuse and adapt them (e.g. from trainings). @muehlhaus

**Comment by kMutagene** [comment]
exporting as svg will not change the base issue being actual _images_ being used to produce the content. those will just be embedded images in the svg (and not be scalable etc.). However i agree that we should export and use everything as svg where possible

**Comment by HLWeil** [comment]
Updated all the slides (and recreated some in the pptx).
